{"name": "Verify error message for login with incorrect credentials -- @1.2 ", "status": "passed", "steps": [{"name": "Given the user is on the login page", "status": "passed", "start": 1751361198396, "stop": 1751361199171}, {"name": "When the user enter the InvalidUser and secret_sauce", "status": "passed", "start": 1751361199171, "stop": 1751361199298}, {"name": "Then the Epic sadface: Username and password do not match any user in this service is displayed", "status": "passed", "start": 1751361199299, "stop": 1751361199309}], "parameters": [{"name": "username", "value": "InvalidUser"}, {"name": "password", "value": "secret_sauce"}, {"name": "error message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1751361198294, "stop": 1751361199356, "uuid": "ad053390-9910-4eb3-879f-297ff6bd3a77", "historyId": "994a2418164dc0cf04f876070e74347f", "fullName": "User login functionality: Verify error message for login with incorrect credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "invalid_user"}, {"name": "tag", "value": "login"}, {"name": "feature", "value": "User login functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}